# Generated by Django 2.2.16 on 2020-10-27 10:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundsMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID of transaction', unique=True)),
                ('credit', models.ForeignKey(help_text='Source', on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transactions', related_query_name='outgoing_transaction', to='accounts.Account')),
                ('debit', models.ForeignKey(help_text='Destination', on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transactions', related_query_name='incoming_transaction', to='accounts.Account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
